"""improve tools

Revision ID: 39dac3a48fdb
Revises: 5b61b04867ef
Create Date: 2021-02-17 17:27:06.683789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39dac3a48fdb'
down_revision = '5b61b04867ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('created_dt', sa.DateTime(), nullable=True))
    op.add_column('tool', sa.Column('modified_dt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'modified_dt')
    op.drop_column('tool', 'created_dt')
    # ### end Alembic commands ###
