"""add created_dt to user_feedback

Revision ID: 52e822035335
Revises: 87aa4182ce68
Create Date: 2021-02-04 03:04:12.587057

"""
from alembic import op
import sqlalchemy as sa
import datetime

# revision identifiers, used by Alembic.
revision = '52e822035335'
down_revision = '87aa4182ce68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_feedback', sa.Column('created_dt', sa.DateTime(), nullable=True))
    op.execute("UPDATE user_feedback SET created_dt = '" + str(datetime.datetime.utcnow()) + "'")
    op.alter_column('user_feedback', 'created_dt', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_feedback', 'created_dt')
    # ### end Alembic commands ###
