"""Add removed_dt to project

Revision ID: 6357364d6380
Revises: 5fcb495224e6
Create Date: 2020-12-08 03:59:20.267370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6357364d6380'
down_revision = '5fcb495224e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('removed_dt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'removed_dt')
    # ### end Alembic commands ###
