"""add user_feedback

Revision ID: 87aa4182ce68
Revises: e1fd98c3609a
Create Date: 2020-12-24 10:45:35.349830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87aa4182ce68'
down_revision = 'e1fd98c3609a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_given_user_id', sa.Integer(), nullable=False),
    sa.Column('feedback_received_user_id', sa.Integer(), nullable=False),
    sa.Column('project_worker_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.CheckConstraint('rating <= 5', name='user_feedback_rating_check_max_5'),
    sa.CheckConstraint('rating >= 0', name='user_feedback_rating_check_positive'),
    sa.ForeignKeyConstraint(['feedback_given_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['feedback_received_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_worker_id'], ['project_worker.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedback_given_user_id', 'feedback_received_user_id', 'project_worker_id', name='uix_user_feedback_given_and_received_user_id_project_worker_id')
    )
    op.create_index(op.f('ix_user_feedback_feedback_given_user_id'), 'user_feedback', ['feedback_given_user_id'], unique=False)
    op.create_index(op.f('ix_user_feedback_feedback_received_user_id'), 'user_feedback', ['feedback_received_user_id'], unique=False)
    op.create_index(op.f('ix_user_feedback_id'), 'user_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_user_feedback_project_worker_id'), 'user_feedback', ['project_worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_feedback_project_worker_id'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_id'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_feedback_received_user_id'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_feedback_given_user_id'), table_name='user_feedback')
    op.drop_table('user_feedback')
    # ### end Alembic commands ###
