"""add nullable to project_workers

Revision ID: 9e2e4ac5a27f
Revises: 1829e668f7b0
Create Date: 2020-12-10 08:15:30.747622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2e4ac5a27f'
down_revision = '1829e668f7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_worker', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_worker', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_worker', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project_worker', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
