"""Add accounting

Revision ID: c24e28685659
Revises: 39dac3a48fdb
Create Date: 2021-02-22 00:22:07.611695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24e28685659'
down_revision = '39dac3a48fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    accounting_transaction_type = op.create_table('accounting_transaction_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('modified_dt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounting_transaction_type_name'), 'accounting_transaction_type', ['name'], unique=True)
    op.create_table('accounting_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.Column('modified_dt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounting_balance_user_id'), 'accounting_balance', ['user_id'], unique=True)
    op.create_table('accounting_hour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('hour_count', sa.Numeric(), nullable=False),
    sa.Column('per_hour_cost', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uix_accounting_hour_user_id_day')
    )
    op.create_index(op.f('ix_accounting_hour_user_id'), 'accounting_hour', ['user_id'], unique=False)
    op.create_table('accounting_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type'], ['accounting_transaction_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounting_transaction_type'), 'accounting_transaction', ['type'], unique=False)
    op.create_index(op.f('ix_accounting_transaction_user_id'), 'accounting_transaction', ['user_id'], unique=False)
    # ### end Alembic commands ###

    op.bulk_insert(accounting_transaction_type,
                   [
                       {'id': 1, 'name': 'Other'},
                       {'id': 2, 'name': 'Payment'},
                       {'id': 3, 'name': 'Correction'},
                     ]
                   )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounting_transaction_user_id'), table_name='accounting_transaction')
    op.drop_index(op.f('ix_accounting_transaction_type'), table_name='accounting_transaction')
    op.drop_table('accounting_transaction')
    op.drop_index(op.f('ix_accounting_hour_user_id'), table_name='accounting_hour')
    op.drop_table('accounting_hour')
    op.drop_index(op.f('ix_accounting_balance_user_id'), table_name='accounting_balance')
    op.drop_table('accounting_balance')
    op.drop_index(op.f('ix_accounting_transaction_type_name'), table_name='accounting_transaction_type')
    op.drop_table('accounting_transaction_type')
    # ### end Alembic commands ###
