"""Fix accounting_hour unique key

Revision ID: d2ce0899a085
Revises: fd8cdbb92a71
Create Date: 2021-03-07 03:39:43.191984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ce0899a085'
down_revision = 'fd8cdbb92a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_accounting_hour_user_id_day', 'accounting_hour', type_='unique')
    op.create_unique_constraint('uix_accounting_hour_user_id_day', 'accounting_hour', ['user_id', 'day'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_accounting_hour_user_id_day', 'accounting_hour', type_='unique')
    op.create_unique_constraint('uix_accounting_hour_user_id_day', 'accounting_hour', ['project_id', 'user_id', 'day'])
    # ### end Alembic commands ###
