"""Fix accounting

Revision ID: f9afc8a5fa08
Revises: e83d032b559b
Create Date: 2021-02-22 22:20:39.952902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9afc8a5fa08'
down_revision = 'e83d032b559b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounting_transaction', sa.Column('type_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_accounting_transaction_type_id'), 'accounting_transaction', ['type_id'], unique=False)
    op.drop_index('ix_accounting_transaction_type', table_name='accounting_transaction')
    op.drop_constraint('accounting_transaction_type_fkey', 'accounting_transaction', type_='foreignkey')
    op.create_foreign_key('accounting_transaction_type_id_fkey', 'accounting_transaction', 'accounting_transaction_type', ['type_id'], ['id'])
    op.drop_column('accounting_transaction', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounting_transaction', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('accounting_transaction_type_id_fkey', 'accounting_transaction', type_='foreignkey')
    op.create_foreign_key('accounting_transaction_type_fkey', 'accounting_transaction', 'accounting_transaction_type', ['type'], ['id'])
    op.create_index('ix_accounting_transaction_type', 'accounting_transaction', ['type'], unique=False)
    op.drop_index(op.f('ix_accounting_transaction_type_id'), table_name='accounting_transaction')
    op.drop_column('accounting_transaction', 'type_id')
    # ### end Alembic commands ###
